### ISSUE TITLE
Fix Required list has not defined properties

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/covid-symptom-annotator-example#1]
### Problem description

The command `python -m openapi_server` throws the following error:

```console
$ python -m openapi_server
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tschaffter/dev2/nlpsandbox/covid-symptom-annotator-example/server/openapi_server/__main__.py", line 19, in <module>
    main()
  File "/home/tschaffter/dev2/nlpsandbox/covid-symptom-annotator-example/server/openapi_server/__main__.py", line 11, in main
    app.add_api('openapi.yaml',
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 57, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/apps/abstract.py", line 144, in add_api
    api = self.api_cls(specification,
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/apis/abstract.py", line 75, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/spec.py", line 153, in load
    return cls.from_file(spec, arguments=arguments)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/spec.py", line 107, in from_file
    return cls.from_dict(spec)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/spec.py", line 145, in from_dict
    return OpenAPISpecification(spec)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/spec.py", line 38, in __init__
    self._validate_spec(raw_spec)
  File "/home/tschaffter/.conda/envs/data-node/lib/python3.9/site-packages/connexion/spec.py", line 239, in _validate_spec
    raise InvalidSpecification.create_from(e)
connexion.exceptions.InvalidSpecification: Required list has not defined properties: ['condition', 'start', 'text', 'certainty', 'confidence', 'length']
```

**Comment by tschaffter** [comment]
I found the issue in `cat server/openapi_server/openapi/openapi.yaml`. The following does not work:

```
    TextCovidSymptomAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextCovidSymptomAnnotation_allOf'
      description: A COVID symptom annotation in a text
      required:
      - certainty
      - condition
      - confidence
      - length
      - start
      - text
```

but this works:

```
    TextCovidSymptomAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextCovidSymptomAnnotation_allOf'
      description: A COVID symptom annotation in a text
```

The issue is because the schemas `TextCovidSymptomAnnotation` does not see the properties listed below `required` within the schemas listed below `allOf:`. The schemas `TextAnnotation` already defines its own required properties. I moved the remaining required properties (`certainty` and `condition`) to the object `TextCovidSymptomAnnotation_allOf`.

I also fixed the official specification [here](https://github.com/nlpsandbox/nlpsandbox-schemas/pull/203).
